# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Browser": "shopping.ipynb"}

modules = ["shopping.py"]

doc_url = "https://thanakijwanavit.github.io/linesdk/"

git_url = "https://github.com/thanakijwanavit/linesdk/tree/master/"

def custom_doc_links(name): return None
